### ISSUE TITLE
Install hg + robustcheckout for generic-worker hosts

### ISSUE THREAD

**Issue by ahal** [mozilla-releng/OpenCloudConfig#120]
I was directed towards this repo. This is for bug 1436037.

To summarize, we want to start using 'run-task' based tasks on OSX and Windows (focusing on OSX first). OSX tests use the generic-worker implementation, so I'm trying to get the [run-task](https://searchfox.org/mozilla-central/source/taskcluster/docker/recipes/run-task) script to work with a generic-worker.

The latest issue I hit is that mercurial isn't installed. We'll also need the [robustcheckout](https://hg.mozilla.org/hgcustom/version-control-tools/file/tip/hgext/robustcheckout) extension installed as well.

I don't see any reference to OSX in this repo, is that controlled somewhere else?

**Comment by ahal** [comment]
I'm told OSX is handled by puppetagain. I'll file a bug over there for that, but this one is still valid as we'll also want these installed on Windows.

**Comment by grenade** [comment]
all production build and test worker types configured by occ have hg and [robustcheckout](https://github.com/search?utf8=%E2%9C%93&q=robustcheckout.py+user%3Amozilla-releng+repo%3AOpenCloudConfig+extension%3Ajson&type=Code&ref=advsearch&l=&l=) installed.
