### ISSUE TITLE
OCC local install on VM (i.e. not in AWS) should omit --configure-for-aws startup option

### ISSUE THREAD

**Issue by petemoore** [mozilla-releng/OpenCloudConfig#61]
In AWS, we run generic worker with:

```
generic-worker.exe run --configure-for-aws
```

whereas outside of AWS we should run with simply:

```
generic-worker.exe run
```

In other words, we should omit the `--configure-for-aws` option in the `C:\generic-worker\run-generic-worker.bat` file.

**Comment by petemoore** [comment]
CC @markcor

**Comment by markcor** [comment]
In a pull request i am submitting next week I will be adding the run-hw-generic-worker-and-reboot.bat. That will contain "C:\generic-worker\generic-worker.exe run --config C:\generic-worker\gen_worker.config" . Because of sensitive data the config is deployed through the MDT.

**Comment by petemoore** [comment]
Thanks!

**Comment by petemoore** [comment]
I think this is done now.
